### ISSUE TITLE
Design logo for SSA Digital Service team

### ISSUE THREAD

**Issue by mollieru** [usds/branding#1]
**Who are you?**
Greg from SSA (via Mollie)

**What kind of design support do you need?**
Visual identity/branding (for a program, group, product, etc.)

**Describe the project/work you need done. The more details the better.**
The new SSA digital service team needs their own visual identity mark much like the USDS and DSVA teams. No color or design constraints that we know of. 

**Who is the audience/users?**
Internal SSA employees, prospective candidates, other stakeholders

**When do you need this by?**
Sooner rather than later (first week of Dec ideally)

*Any links or materials we can look at to get started?*
ssa.gov

**Comment by KHarshawat** [comment]
Adding the Agency Seal for inspiration :)

![ssa](https://cloud.githubusercontent.com/assets/6335546/12901477/fda4a046-ce89-11e5-9cfa-89721c9b8145.png)

**Comment by mollieru** [comment]
closing and moving to main repo...https://github.com/usds/usds/issues/1154
