### ISSUE TITLE
Design logo for DHS Digital Service 

### ISSUE THREAD

**Issue by mollieru** [usds/branding#2]
**Who are you?**
Eric Hysen

**What kind of design support do you need? Please select one or more:**
Visual identity/branding (for a program, group, product, etc.) 
Title: "DHS Digital Service"

**Who is the audience/users?**
People and things

**When do you need this by?**
Sometime

**Any links or materials we can look at to get started?**
The internet

**Anything else you want us to know?**
Mollie's the best.

**Comment by KHarshawat** [comment]
Adding the Agency Seal for inspiration :)

![dhs](https://cloud.githubusercontent.com/assets/6335546/12901485/0cedb1b4-ce8a-11e5-870c-e6c0f11f5090.png)

**Comment by mollieru** [comment]
Moving to the main repo here: https://github.com/usds/usds/issues/1153
