### ISSUE TITLE
Design logo for Defense Digital Service team

### ISSUE THREAD

**Issue by mollieru** [usds/branding#3]
**Who are you?**
Chris

**What kind of design support do you need? Please select one or more:**
Visual identity/branding (for a program, group, product, etc.) 
Title: "Defense Digital Service"

**Who is the audience/users?**
People and things

**When do you need this by?**
end of 2nd week of Dec

**Any links or materials we can look at to get started?**
Defense's website

**Anything else you want us to know?**
Mollie's the best.

**Comment by KHarshawat** [comment]
Adding the Agency Seal for inspiration :)

![dod](https://cloud.githubusercontent.com/assets/6335546/12901507/1e92dd36-ce8a-11e5-81ea-1deab20fd2ac.png)

**Comment by mollieru** [comment]
This project has been completed a few weeks ago -- will close out the issue shortly.



Mollie Ruskin
U.S. Digital Service

-----Original Message-----
