### ISSUE TITLE
Add DS@VA branding materials to this repo

### ISSUE THREAD

**Issue by alex** [usds/branding#4]
Would be great to have them all in one place!

**Comment by mollieru** [comment]
CC @KHarshawat -- are you still the owner of that stuff?

**Comment by mollieru** [comment]
pingping @KHarshawat we can haz DS VA brand stuffs here? 😬

**Comment by mollieru** [comment]
@KHarshawat _hello. it's me. I was wondering if after all these years you'd like to..._

...add the VA Digital Service team logo so that it can be in the public domain and all the USDS team logos can be in one place?

**Comment by KHarshawat** [comment]
@mollieru Gah!! Thanks for the ping. I finally added our logos here: https://github.com/usds/branding/tree/master/DSteamlogos/DSVA%20Branding%20Materials

Do you want other brand assets such as PowerPoint, Word, and Keynote templates? If so, where do you want those to go (branding/templates or somewhere else)? 

Also is there a specific naming convention you'd prefer? I can change the files I added and others I might add to reflect your preference.
