### ISSUE TITLE
Add DHS logo files

### ISSUE THREAD

**Issue by mollieru** [usds/branding#9]
When you have a moment @efortiz can you upload your DHS logo assets here? thanks!

**Comment by efortiz** [comment]
[DHS DS Logo assets.zip](https://github.com/usds/branding/files/275230/DHS.DS.Logo.assets.zip)

All assets uploaded. Please note that these will evolve based on the specific use of the logo (i.e.: different backgrounds / etc -- it is currently designed to be used on a white background).

/c @ehysen
